mine_blog:
    resource: "@MineBlogBundle/Controller/"
    type:     annotation
    prefix:   /

mine_minecraft:
    resource: "@MineMinecraftBundle/Controller/"
    type:     annotation
    prefix:   /

mine_web:
    resource: "@MineWebBundle/Controller/"
    type:     annotation
    prefix:   /

mine_user:
    resource: "@MineUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile